// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOPskEzDRitmfPfESunQopQbkzC4ozKf4',
    appId: '1:474773528324:web:79c93c237be8bb15e93a51',
    messagingSenderId: '474773528324',
    projectId: 'instagram-d5aaf',
    authDomain: 'instagram-d5aaf.firebaseapp.com',
    storageBucket: 'instagram-d5aaf.appspot.com',
    measurementId: 'G-ZB93X49DGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-YpFkuQK6z6IZ7ZqNvdoytAQqPtfyHD8',
    appId: '1:474773528324:android:01208c5392fae58de93a51',
    messagingSenderId: '474773528324',
    projectId: 'instagram-d5aaf',
    storageBucket: 'instagram-d5aaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBasBsNftD3c5oUr-V9CMOmtK8uge_nT6M',
    appId: '1:474773528324:ios:a00309045f9b137be93a51',
    messagingSenderId: '474773528324',
    projectId: 'instagram-d5aaf',
    storageBucket: 'instagram-d5aaf.appspot.com',
    iosBundleId: 'com.example.instagram',
  );
}
